ingles = {
#faltacerrarllave
'the':'el/la/los/las',
'of':'de',
'to':'a/hacia',
'and':'y',
'a':'un/una',
'in':'en',
'is':'es',
'it':'eso',
'you':'tú/ustedes',
'that':'ese',
'he';'él',
'was':'estaba',
'for':'para',
'on':'en/sobre',
'are':'son/están',
'with':'con',
'as':'como',
'I':'yo',
'his':'su (de él)',
'they':'ellos/ellas',
'be':'ser/estar',
'at':'a',
'one':'uno',
'have':'tener',
'this':'esta/esto',
'from':'de',
'or':'o',
'had':'tenido',
'by':'por',
'hot':'caliente',
'word':'palabra',
'but':'pero',
'what':'qué',
'some':'algunos',
'we':'nosotros',
'can':'poder',
'out':'fuera',
'other':'otro',
'were':'fueron',
'all':'todas',
'there':'ahí',
'when':'cuando',
'up':'arriba',
'use':'utilizar',
'your':'Su/vuestro(s)/vuestra(s)',
'how':'cómo,
'said':'dijo',
'an':'un',
'each':'cada',
'she':'ella',
'which':'cual',
'do':'hacer',
'their':'su (de ellos)',
'time':'hora/tiempo',
'if':'Si (como condicional)',
'will':'será',
'way':'camino',
'about':'acerca de',
'many':'muchos',
'then':'entonces',
'them':'ellos,
'write':'escribir',
'would':'haría,
'like':'me gusta',
'so':'asi que',
'these':'estas',
'her':'su (de ella)',
'long':'largo',
'make':'hacer',
'thing':'cosa',
'see':'ver',
'him':'él',
'two':'dos',
'has':'tiene',
'look':'Mira',
'more':'Más',
'day':'día',
'could':'podría',
'go':'ir',
'come':'ven',
'did':'hizo',
'number':'número',
'sound':'sonar',
'no':'no',
'most':'más',
'people':'gente',
'my':'mi/gente',
'over':'encima/sobre',
}

buscar = input("que palabra desea buscar?")
for key in ingles:
  print key, ":", ingles[key]
  


